
Uno:

```
Excepción atrapada en el bloque catch
Fin.
```

---

Dos:

```
Excepción atrapada en el bloque catch
Dentro del bloque finally
Fin.
```

---

Tres:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 4
    at Tres.main(Tres.java:12)
```

---

Cuatro:

```
Dentro del bloque finally
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 4
    at Cuatro.main(Cuatro.java:12)
```

---

Cinco:

```
Dentro del bloque try
Fin.
```

---

Seis:

```
try block fully executed
Dentro del bloque finally
Fin.
```

---

Siete:

```
Dentro del bloque finally
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 4
    at Siete.main(Siete.java:11)
```

---

Ocho:

```
Dentro del bloque try
Dentro del bloque finally
Fin.
```
